#!/bin/bash
set -o pipefail # exit status 0 only if all cmds 0
set -e # exit immediately upon failure
set -x # log all cmds before executing

DEPLOY_DIR=/tmp/deploy/test
DEPLOY_BRANCH="refs/heads/master"

while read -r oldrev newrev ref
do
  if [[ $ref != $DEPLOY_BRANCH ]]; then
    echo "Not a deployable branch"
    exit 1
  fi
  git --work-tree=$DEPLOY_DIR checkout --force --detach $newrev
done
